name: Android 14 5.15
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  push:
    paths:
      - .github/workflows/kernel-a14-5.15.yml  # Runs when this workflow file is updated\
  workflow_dispatch:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
        default: Next
      kernelsu_branch:
        required: true
        type: string
        default: Stable
      kernelsu_branch_other:
        required: false
        type: string
        default: ""
  
jobs:
  build-kernel-a14-5-15-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "131"
            os_patch_level: "2023-11"
          - sub_level: "137"
            os_patch_level: "2024-01"
          - sub_level: "144"
            os_patch_level: "2024-03"
          - sub_level: "148"
            os_patch_level: "2024-05"
          - sub_level: "149"
            os_patch_level: "2024-06"
          - sub_level: "153"
            os_patch_level: "2024-07"
          - sub_level: "158"
            os_patch_level: "2024-08"
          - sub_level: "167"
            os_patch_level: "2024-11"
          - sub_level: "170"
            os_patch_level: "2025-01"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release || false }}
      android_version: "android14"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'Next' }}
      kernelsu_branch: ${{ inputs.kernelsu_branch || 'Dev' }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
