name: Android 15 6.6
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  push:
    paths:
      - .github/workflows/kernel-a15-6.6.yml  # Runs when this workflow file is updated\
  workflow_dispatch:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
        default: Next
      kernelsu_branch:
        required: true
        type: string
        default: Stable
      kernelsu_branch_other:
        required: false
        type: string
        default: ""

jobs:
  build-kernel-a15-6-6-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- sub_level: "30"
          #  os_patch_level: "2024-08"
          #- sub_level: "46"
          #  os_patch_level: "2024-09"
          - sub_level: "50"
            os_patch_level: "2024-10"
          - sub_level: "56"
            os_patch_level: "2024-11"
          - sub_level: "57"
            os_patch_level: "2024-12"
          - sub_level: "58"
            os_patch_level: "2025-01"
          - sub_level: "66"
            os_patch_level: "2025-02"
          - sub_level: "77"
            os_patch_level: "2025-03"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release || false }}
      android_version: "android15"
      kernel_version: "6.6"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'Next' }}
      kernelsu_branch: ${{ inputs.kernelsu_branch || 'Dev' }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
