name: Test GKI Build
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  push:
    paths:
      - .github/workflows/test-build.yml  # Runs when this workflow file is updated\
      - .github/workflows/gki-kernel.yml  # Runs when this workflow file is updated\
  workflow_dispatch:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
        default: Next
      kernelsu_branch:
        required: true
        type: string
        default: Stable
      kernelsu_branch_other:
        required: false
        type: string
        default: ""
  
jobs:
  build-test-kernel-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
        - android_version: "android12"
          kernel_version: "5.10"
          sub_level: "X"
          os_patch_level: "lts"
          revision: "r1"
        - android_version: "android13"
          kernel_version: "5.10"
          sub_level: "X"
          os_patch_level: "lts"
        - android_version: "android13"
          kernel_version: "5.15"
          sub_level: "X"
          os_patch_level: "lts"
        - android_version: "android14"
          kernel_version: "5.15"
          sub_level: "X"
          os_patch_level: "lts"
        - android_version: "android14"
          kernel_version: "6.1"
          sub_level: "X"
          os_patch_level: "lts"
        - android_version: "android15"
          kernel_version: "6.6"
          sub_level: "X"
          os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release || false }}
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      revision: ${{ matrix.revision }}
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'Next' }}
      kernelsu_branch: ${{ inputs.kernelsu_branch || 'Dev' }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
